###############################################################################
# Copyright 2017 Samsung Electronics All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
###############################################################################

################ EZMQ sample build script ##################
Import('env')

target_os = env.get('TARGET_OS')
ezmq_sample_env = env.Clone()

######################################################################
# Build flags
######################################################################
ezmq_sample_env.AppendUnique(CPPPATH=[
    '../extlibs/zmq',
    '../protobuf',
    '../include',
    '../src',
    '../dependencies/libzmq/include',
    '../dependencies/protobuf-3.4.0/src/',
])

if target_os not in ['windows']:
    ezmq_sample_env.AppendUnique(
            CXXFLAGS=['-O2', '-g', '-Wall', '-fmessage-length=0', '-std=c++0x', '-I/usr/local/include'])
    ezmq_sample_env.AppendUnique(LIBS=['ezmq', 'protobuf'])
else:
    if env.get('SECURED') == '1':
        ezmq_sample_env.AppendUnique(LIBS=File('#/dependencies/libsodium/bin/x64/Release/v140/static/libsodium.lib'))
    ezmq_sample_env.AppendUnique(LIBS=File('#/dependencies/libzmq/bin/x64/Release/v140/static/libzmq.lib'))
    ezmq_sample_env.AppendUnique(LIBS=File('#/dependencies/protobuf-3.4.0/cmake/build/solution/Release/libprotobuf.lib'))
    if not env.get('RELEASE'):
        ezmq_sample_env.AppendUnique(LIBS=File('#/out/windows/win32/amd64/debug/ezmq.lib'))
    else:
        ezmq_sample_env.AppendUnique(LIBS=File('#/out/windows/win32/amd64/release/ezmq.lib'))

####################################################################
# Source files and Targets
######################################################################
ezmqpublisher = ezmq_sample_env.Program('publisher', 'publisher.cpp')
ezmqsubscriber = ezmq_sample_env.Program('subscriber', 'subscriber.cpp')